apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  annotations:
    rafay.dev/audit_type: BROWSER||Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)
      AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
    rafay.dev/audit_user: giridharaprasad@rafay.co
    rafay.dev/audit_user_group: Organization Admins,giri
  description: version-description
  name: nginx-upload
  project: giri-may
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/nginx-upload/nginx-15.4.2.tgz
      valuesPaths:
      - name: file://artifacts/nginx-upload/values.yaml
    type: Helm
  namespace: nginx
  sharing:
    enabled: true
    projects:
    - name: giri-nov
    - name: giri-np
  version: v1
