apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: giri-mks-oct17
  project: giri-may
spec:
  blueprint:
    name: minimal
  config:
    autoApproveNodes: true
    installerTtl: 365
    kubernetesVersion: v1.30.4
    network:
      cni:
        name: Calico
        version: 3.28.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
  proxy: {}
  type: mks
