apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: test-golden-old-cilium-bp
  project: giri-may
spec:
  base:
    name: default-aks
    version: 2.7.0
  defaultAddons:
    enableMonitoring: true
    monitoring:
      metricsServer:
        customizationEnabled: true
      prometheusAdapter:
        customizationEnabled: true
  driftWebhook:
    enabled: true
  networkPolicy:
    profile:
      name: default
      version: latest
  type: golden
  version: v2
