apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: test-custom-old-cilium-bp
  project: giri-may
spec:
  base:
    name: test-golden-old-cilium-bp
    version: v2
  defaultAddons:
    enableMonitoring: true
    monitoring:
      metricsServer:
        customizationEnabled: true
      prometheusAdapter:
        customizationEnabled: true
  driftWebhook:
    enabled: true
  type: custom
  version: v1
